name: BTGraves
version: '${project.version}'
main: dev.pluginz.graveplugin.GravePlugin
api-version: 1.13
description: A plugin to create graves on player death.
permissions:
  btgraves.reload:
    description: Allows access to all graves.
    default: op
  btgraves.admin.open:
    description: Allows admins to open a grave using the Grave ID
    default: op
commands:
  grave:
    description: Grave management command
    usage: /grave <subcommand>
